# The ReShade version Setup installs is pinned at build time with the SHA-256 of its installer. Writes
# installer-generated/pinned.h, which Setup includes.

set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/vendor/reshade/reshade.ini")
file(STRINGS "${CMAKE_SOURCE_DIR}/vendor/reshade/reshade.ini" RESHADE_VERSION REGEX "^version=")
file(STRINGS "${CMAKE_SOURCE_DIR}/vendor/reshade/reshade.ini" RESHADE_SETUP_SHA256 REGEX "^sha256=")
string(REGEX REPLACE "^version=" "" RESHADE_VERSION "${RESHADE_VERSION}")
string(REGEX REPLACE "^sha256=" "" RESHADE_SETUP_SHA256 "${RESHADE_SETUP_SHA256}")
string(STRIP "${RESHADE_VERSION}" RESHADE_VERSION)
string(STRIP "${RESHADE_SETUP_SHA256}" RESHADE_SETUP_SHA256)
string(TOLOWER "${RESHADE_SETUP_SHA256}" RESHADE_SETUP_SHA256)
string(LENGTH "${RESHADE_SETUP_SHA256}" length)
if(NOT RESHADE_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "vendor/reshade/reshade.ini needs a line such as version=6.8.0.")
endif()
if(NOT length EQUAL 0 AND (NOT length EQUAL 64 OR NOT RESHADE_SETUP_SHA256 MATCHES "^[0-9a-f]+$"))
    message(FATAL_ERROR "The sha256 line in vendor/reshade/reshade.ini is not a SHA-256.")
endif()

# With a hash, the download checks it, so a wrong hash fails here instead of in Setup. Without one, the hash of what
# reshade.me sends now is used, and the maintainer is told the line to commit.
set(RESHADE_SETUP_URL "https://reshade.me/downloads/ReShade_Setup_${RESHADE_VERSION}_Addon.exe")
set(RESHADE_SETUP_FILE "${CMAKE_BINARY_DIR}/reshade/ReShade_Setup_${RESHADE_VERSION}_Addon.exe")
if(RESHADE_SETUP_SHA256)
    if(EXISTS "${RESHADE_SETUP_FILE}")
        file(SHA256 "${RESHADE_SETUP_FILE}" cached)
        if(NOT cached STREQUAL RESHADE_SETUP_SHA256)
            file(REMOVE "${RESHADE_SETUP_FILE}")
        endif()
    endif()
    fetch_file("${RESHADE_SETUP_URL}" ${RESHADE_SETUP_SHA256} "${RESHADE_SETUP_FILE}")
else()
    set(reason "")
    if(NOT EXISTS "${RESHADE_SETUP_FILE}")
        file(DOWNLOAD "${RESHADE_SETUP_URL}" "${RESHADE_SETUP_FILE}.part" STATUS status)
        list(GET status 0 code)
        # An error page sent with a success status is not a program.
        if(code EQUAL 0)
            file(READ "${RESHADE_SETUP_FILE}.part" magic LIMIT 2 HEX)
            if(NOT magic STREQUAL "4d5a")
                set(code 1)
                set(status "1;reshade.me did not send a program")
            endif()
        endif()
        if(code EQUAL 0)
            file(RENAME "${RESHADE_SETUP_FILE}.part" "${RESHADE_SETUP_FILE}")
        else()
            file(REMOVE "${RESHADE_SETUP_FILE}.part")
            list(GET status 1 reason)
            string(REPLACE "\"" "" reason "${reason}")
        endif()
    endif()
    if(EXISTS "${RESHADE_SETUP_FILE}")
        file(SHA256 "${RESHADE_SETUP_FILE}" RESHADE_SETUP_SHA256)
        message(WARNING "vendor/reshade/reshade.ini has no SHA-256 for ReShade ${RESHADE_VERSION}, so this build of Setup "
                        "trusts the copy reshade.me sent now. To pin it, commit this line to vendor/reshade/reshade.ini:\n"
                        "sha256=${RESHADE_SETUP_SHA256}")
    else()
        message(WARNING "vendor/reshade/reshade.ini has no SHA-256 for ReShade ${RESHADE_VERSION}, and ${RESHADE_SETUP_URL} "
                        "could not be downloaded to compute it (${reason}). Setup cannot be built until the sha256 line is "
                        "filled in.")
    endif()
endif()

set(SETUP_GENERATED_DIR "${CMAKE_BINARY_DIR}/installer-generated")
configure_file("${CMAKE_SOURCE_DIR}/installer/pinned.h.in" "${SETUP_GENERATED_DIR}/pinned.h" @ONLY)
