# What Setup downloads is pinned at build time: the ReShade version it installs with the SHA-256 of its installer, and
# the name and SHA-256 of every add-on file. A download list or release asset changed later cannot change what Setup
# runs or installs. Writes installer-generated/pinned.h, which Setup includes.

file(STRINGS "${CMAKE_SOURCE_DIR}/vendor/reshade/reshade.ini" RESHADE_VERSION REGEX "^version=")
file(STRINGS "${CMAKE_SOURCE_DIR}/vendor/reshade/reshade.ini" RESHADE_SETUP_SHA256 REGEX "^sha256=")
string(REGEX REPLACE "^version=" "" RESHADE_VERSION "${RESHADE_VERSION}")
string(REGEX REPLACE "^sha256=" "" RESHADE_SETUP_SHA256 "${RESHADE_SETUP_SHA256}")
string(STRIP "${RESHADE_VERSION}" RESHADE_VERSION)
string(STRIP "${RESHADE_SETUP_SHA256}" RESHADE_SETUP_SHA256)
string(TOLOWER "${RESHADE_SETUP_SHA256}" RESHADE_SETUP_SHA256)
string(LENGTH "${RESHADE_SETUP_SHA256}" length)
if(NOT RESHADE_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "vendor/reshade/reshade.ini needs a line such as version=6.8.0.")
endif()
if(NOT length EQUAL 0 AND (NOT length EQUAL 64 OR NOT RESHADE_SETUP_SHA256 MATCHES "^[0-9a-f]+$"))
    message(FATAL_ERROR "The sha256 line in vendor/reshade/reshade.ini is not a SHA-256.")
endif()

# With a hash, the download checks it, so a wrong hash fails here instead of in Setup. Without one, the hash of what
# reshade.me sends now is used, and the maintainer is told the line to commit.
set(RESHADE_SETUP_URL "https://reshade.me/downloads/ReShade_Setup_${RESHADE_VERSION}_Addon.exe")
set(RESHADE_SETUP_FILE "${CMAKE_BINARY_DIR}/reshade/ReShade_Setup_${RESHADE_VERSION}_Addon.exe")
if(RESHADE_SETUP_SHA256)
    if(EXISTS "${RESHADE_SETUP_FILE}")
        file(SHA256 "${RESHADE_SETUP_FILE}" cached)
        if(NOT cached STREQUAL RESHADE_SETUP_SHA256)
            file(REMOVE "${RESHADE_SETUP_FILE}")
        endif()
    endif()
    fetch_file("${RESHADE_SETUP_URL}" ${RESHADE_SETUP_SHA256} "${RESHADE_SETUP_FILE}")
else()
    set(reason "")
    if(NOT EXISTS "${RESHADE_SETUP_FILE}")
        file(DOWNLOAD "${RESHADE_SETUP_URL}" "${RESHADE_SETUP_FILE}.part" STATUS status)
        list(GET status 0 code)
        if(code EQUAL 0)
            file(RENAME "${RESHADE_SETUP_FILE}.part" "${RESHADE_SETUP_FILE}")
        else()
            file(REMOVE "${RESHADE_SETUP_FILE}.part")
            list(GET status 1 reason)
            string(REPLACE "\"" "" reason "${reason}")
        endif()
    endif()
    if(EXISTS "${RESHADE_SETUP_FILE}")
        file(SHA256 "${RESHADE_SETUP_FILE}" RESHADE_SETUP_SHA256)
        message(WARNING "vendor/reshade/reshade.ini has no SHA-256 for ReShade ${RESHADE_VERSION}, so this build of Setup "
                        "trusts the copy reshade.me sent now. To pin it, commit this line to vendor/reshade/reshade.ini:\n"
                        "sha256=${RESHADE_SETUP_SHA256}")
    else()
        message(WARNING "vendor/reshade/reshade.ini has no SHA-256 for ReShade ${RESHADE_VERSION}, and ${RESHADE_SETUP_URL} "
                        "could not be downloaded to compute it (${reason}). Setup cannot be built until the sha256 line is "
                        "filled in.")
    endif()
endif()

# Reads an add-on manifest from vendor/. Appends its files to files_variable as { L"name", "sha256" }, and the GitHub
# release or Hugging Face repository each of its URLs points into to sources_variable as host|/path/.
function(read_addon_manifest manifest files_variable sources_variable)
    file(STRINGS "${manifest}" lines)
    set(files "")
    set(sources "${${sources_variable}}")
    set(hashed "")
    set(linked "")
    set(section "")
    foreach(line IN LISTS lines)
        string(STRIP "${line}" line)
        if(line MATCHES "^\\[(.*)\\]$")
            set(section "${CMAKE_MATCH_1}")
        elseif(line MATCHES "^sha256=(.*)$")
            string(TOLOWER "${CMAKE_MATCH_1}" hash)
            string(LENGTH "${hash}" length)
            if(NOT section MATCHES "^[A-Za-z0-9._-]+$" OR NOT length EQUAL 64 OR NOT hash MATCHES "^[0-9a-f]+$")
                message(FATAL_ERROR "${manifest} has an invalid sha256 line in [${section}].")
            endif()
            list(APPEND files "{ L\"${section}\", \"${hash}\" }")
            list(APPEND hashed "${section}")
        elseif(line MATCHES "^url=https://github\\.com(/[A-Za-z0-9._-]+/[A-Za-z0-9._-]+/releases/download/)")
            list(APPEND sources "github.com|${CMAKE_MATCH_1}")
            list(APPEND linked "${section}")
        elseif(line MATCHES "^url=https://huggingface\\.co(/[A-Za-z0-9._-]+/[A-Za-z0-9._-]+/resolve/)")
            list(APPEND sources "huggingface.co|${CMAKE_MATCH_1}")
            list(APPEND linked "${section}")
        elseif(line MATCHES "^url=")
            message(FATAL_ERROR "${manifest}: [${section}] must download from a GitHub release or a Hugging Face repository.")
        endif()
    endforeach()
    if(NOT files OR NOT hashed STREQUAL linked)
        message(FATAL_ERROR "${manifest} must list each file with a url and a sha256 line.")
    endif()
    string(JOIN ", " files ${files})
    set(${files_variable} "${files}" PARENT_SCOPE)
    set(${sources_variable} "${sources}" PARENT_SCOPE)
endfunction()

set(addon_sources "")
read_addon_manifest("${CMAKE_SOURCE_DIR}/vendor/depth/downloads.ini" DEPTH_FILES addon_sources)
read_addon_manifest("${CMAKE_SOURCE_DIR}/vendor/dlss5/downloads.ini" DLSS5_FILES addon_sources)
list(REMOVE_DUPLICATES addon_sources)
set(ADDON_SOURCES "")
foreach(source IN LISTS addon_sources)
    string(REPLACE "|" "\", L\"" source "${source}")
    list(APPEND ADDON_SOURCES "{ L\"${source}\" }")
endforeach()
string(JOIN ", " ADDON_SOURCES ${ADDON_SOURCES})

set(SETUP_GENERATED_DIR "${CMAKE_BINARY_DIR}/installer-generated")
configure_file("${CMAKE_SOURCE_DIR}/installer/pinned.h.in" "${SETUP_GENERATED_DIR}/pinned.h" @ONLY)
